teaching_management/Myauth/urls.py
from django.urls import path, include
from . import views

app_name = 'Myauth'
urlpatterns = [
    path('', views.user_login, name='登录'),
    path('homepage/', views.homepage, name='学生主页'),
    path('homepage_t/', views.homepage_t, name='老师主页'),
    path('homepage_m/', views.homepage_m, name='管理员主页'),
    path('modifypwd/', views.modifypwd, name='修改密码'),
    path('verifylogin/', views.verify_login, name='验证'),
    path('exit/', views.exit, name='退出'),
    path('updatepwd/', views.updatePwd, name='修改'),
    path('findback/', views.findBack, name='找回'),
    path('findbackpwd/', views.findBackpwd, name='找回密码'),
    path('reset/', views.reSet, name='重置'),
    path('resetpwd/', views.reSetpwd, name='重置密码'),
    path('class_schedule/', views.class_schedule, name='学生课程表'),
    path('class_schedule_t/', views.class_schedule_t, name='教师课程表'),
    path('get_classschedule/', views.get_classschedule, name='显示课程'),
    path('student_information/', views.student_information, name='学生信息'),
    path('Teacher_Information/', views.teacher_information, name='教师信息'),
    path('Manager_Information/', views.manager_information, name='管理员信息'),
    path('modify_Information/', views.modify_information, name='修改个人信息'),
    path('modify_manager_Information/', views.modify_Manager_Information, name='修改管理员信息'),
    path(r'pag<int:pIndex>/', views.input_course_m, name='录入课程'),
    path('search<int:pIndex>/', views.search_course, name='查看课程'),
    path('add_course_index/', views.add_course_index, name='添加课程页'),
    path('add_course/', views.add_course, name='添加课程'),
    path('delete_course/', views.delete_course, name='删除课程'),
    path('select_course<int:pIndex>/', views.select_course, name="选课"),
    path('student_save/', views.student_save_course, name="学生保存课程"),
    path('select_person/', views.select_person, name="审核个人信息"),
    path('person_detail<str:username>/', views.person_detail, name="个人详情页"),
    path('modify_user>/', views.modify_user, name="修改用户信息"),
    path('register/', views.register, name='注册'),
    path('in_excel/', views.in_excel, name='批量注册'),
    path('signal_register/', views.signal_register, name='单个注册'),
    path('find_selected<int:pIndex>/', views.find_selected, name='查看所选课'),
    path('withdraw_course/', views.withdraw_course, name='学生删除课程'),
    path('delete_teacher/', views.delete_teacher, name='删除教师用户'),
    path('delete_student/', views.delete_student, name='删除学生用户'),
    path('testmanage/', views.testmanage, name='考试编排页'),
    path('add_test/', views.add_test, name='添加考试'),
    path('select_test_info/', views.select_test_info, name='查看考试信息'),
    path('update_test_info/', views.update_test_info, name='更新考试信息'),
    path('delete_test_info/', views.delete_test_info, name='删除考试信息'),
    path('select_student_test/', views.select_student_test, name='查看学生考试信息'),
    path('select_teacher_test/', views.select_teacher_test, name='查看老师考试信息'),
    path('addclbumindex/', views.addclbumindex, name='添加班级页'),
    path('addclbum/', views.addclbum, name='添加班级'),
    path('insertsoreindex/', views.insertSoreIndex, name='录入成绩页'),
    path('insertsore/', views.insertSore, name='批量导入成绩'),
    path('selectcourseindex/', views.selectCourseIndex, name='查看成绩页'),
    path('searchscore/', views.searchScore, name='搜索学生成绩'),
    path('selectsoreindex/', views.selectScoreIndex, name='老师查看成绩'),
    path('modifyscore/', views.modifyScore, name='修改分数'),
    path('selectstudentscore/', views.selectStudentScoreIndex, name='查看学生成绩'),
    path('analysescore/', views.analyseScoreIndex, name='老师成绩分析'),
    path('analystudentsescore/', views.analyStudentseScoreIndex, name='学生成绩分析'),
    path('meanscore/',views.meanScore,name='各班级平均分'),
    path('minscore/',views.minScore,name='各班级最低分'),
    path('maxscore/',views.maxScore,name='各班级最高分'),
    path('varscore/',views.varScore,name='各班级标准差'),
    path('changescore/',views.changeScore,name='各班级变异系数'),
    path('nicescore/',views.niceScore,name='各班级优生率'),
    path('goodscore/',views.goodScore,name='各班级及格率'),
    path('stdscore/',views.stdScore,name='各班级标准差'),
    path('tscore/',views.tScore,name='各班级T分数'),
    path('scorelayer/',views.scoreLayer,name='学生成绩分布图'),
    path('find_person/',views.findPerson,name='查找人'),
    path('comparescore/',views.compareScore,name='比较成绩'),
    path('compareindex/',views.compareIndex,name='比较成绩页'),
    path('collectbar/',views.collectBar,name='成绩总图'),
    path('courseCollect/',views.courseCollect,name='单科总图'),
    path('manyCompare/',views.manyCompare,name='综合比较'),
    path('manyCompareIndex/',views.manyCompareIndex,name='综合比较页'),
]

teaching_management/teaching_management/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Myauth.urls')),
]

teaching_management/Myauth/forms.py
from django import forms


class UserForm(forms.Form):
    name = forms.CharField(label='用户账号', max_length=50)
    password = forms.CharField(label='密码', max_length=50, widget=forms.PasswordInput)

teaching_management/Myauth/views.py
import random
import time
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from .models import StudentInformation, TeacherInformation, User, ManagerInformation, CourseInformation, \
    Course_to_student, Department, Clbum, Course_to_clbum, Course_to_test, Test, Score
from .forms import UserForm
from django.http import HttpResponse, JsonResponse
import json
from .sendmessage import *
from django.core.paginator import Paginator
# filter() 等方法中的关键字参数查询都是一起进行“AND” 的。 如果需要执行更复杂的查询（例如OR 语句），使用Q 对象。
# Q 对象 (django.db.models.Q) 对象用于封装一组关键字参数。这些关键字参数就是上面“字段查询” 中所提及的那些。
from django.db.models import Q
import datetime
import numpy as np
import math
from pyecharts.charts import Bar, Line, Timeline, Page
from pyecharts import options as opts
import copy


# from apps.utils.email_send import send_register_email


# Create your views here.
def decorator(func):
    def innerfunc(request):
        try:
            username = request.session["username"]
        except Exception as e:
            return redirect("Myauth:登录")
        return func(request)

    return innerfunc


def findBack(request):
    return render(request, "Myauth/test.html")


def findBackpwd(request):
    em = request.GET.get("email")
    try:
        try:
            user = StudentInformation.objects.get(email=em)
            e = EmailManage(receivers=[user.email], username=user.student)
            e.sendEmail()
            return HttpResponse("1")
        except:
            try:
                user = TeacherInformation.objects.get(email=em)
                e = EmailManage(receivers=[user.email], username=user.teacher)
                e.sendEmail()
                return HttpResponse('1')
            except:
                user = ManagerInformation.objects.get(email=em)
                e = EmailManage(receivers=[user.email], username=user.manager)
                e.sendEmail()
                return HttpResponse('1')

    except:
        return HttpResponse("0")


def reSet(request):
    user = User.objects.get(pk=request.GET.get("username"))
    request.session['username'] = user.name
    return render(request, "Myauth/test1.html")


def reSetpwd(request):
    user = User.objects.get(name=request.session.get("username"))
    user.password = request.GET.get("password")
    user.save()
    del request.session['username']
    return JsonResponse({"usertype": user.user_type, "label": 1})


@decorator
def homepage(request):
    username = request.session.get('username')
    user = User.objects.get(name=username)
    if user.user_type == 1:
        studentinfo = StudentInformation.objects.get(student_id=username)
        return render(request, 'Myauth/homepage.html', {'studentinfo': studentinfo})


@decorator
def homepage_t(request):
    username = request.session.get('username')
    user = User.objects.get(name=username)
    if user.user_type == 2:
        teacherinfo = TeacherInformation.objects.get(teacher_id=username)
        return render(request, 'Myauth/homepage_t.html', {'teacherinfo': teacherinfo})


@decorator
def homepage_m(request):
    username = request.session.get('username')
    user = User.objects.get(name=username)
    if user.user_type == 0:
        managerinfo = ManagerInformation.objects.get(manager_id=username)
        return render(request, 'Myauth/homepage_m.html', {'managerinfo': managerinfo})


def user_login(request):
    return render(request, 'Myauth/login.html')


def verify_login(request):
    error_reaction = {"errorCode": 0, "errorsList": ''}
    if request.method == 'GET':
        username = request.GET.get('username')
        userpassword = request.GET.get('password')
        if username and userpassword:
            username = username.strip()
            try:
                user = User.objects.get(name=username)
                if user.password == userpassword:
                    if user.user_type == 1:
                        request.session['username'] = user.name
                        return JsonResponse(error_reaction)
                    elif user.user_type == 2:
                        error_reaction['errorCode'] = 2
                        request.session['username'] = user.name
                        return JsonResponse(error_reaction)
                    elif user.user_type == 0:
                        error_reaction['errorCode'] = 3
                        request.session['username'] = user.name
                        return JsonResponse(error_reaction)
                else:
                    error_reaction['errorCode'] = 1
                    error_reaction['errorsList'] = '你输入的密码错误！'
            except:
                error_reaction['errorCode'] = 1
                error_reaction['errorsList'] = '你输入的账号并不存在！'
        return JsonResponse(error_reaction)


# ----------------------------------------------------------------------------------以及modifypwd.html
@decorator
def modifypwd(request):
    user = User.objects.get(name=request.session['username'])
    label = 'Myauth/base.html'
    if user.user_type == 1:
        label
    elif user.user_type == 2:
        label = 'Myauth/base_t.html'
    else:
        label = 'Myauth/base_m.html'
    return render(request, 'Myauth/modifypwd.html', {"label": label, "type": user.user_type})


@decorator
def modify_information(request):
    username = request.session.get('username')
    user = User.objects.get(name=username)
    if user.user_type == 2:
        teacherinfo = TeacherInformation.objects.get(teacher_id=username)
        teacherinfo.phone = request.GET.get('tel')
        teacherinfo.email = request.GET.get('email')
        teacherinfo.save()
    elif user.user_type == 1:
        studentinfo = StudentInformation.objects.get(student_id=username)
        studentinfo.phone = request.GET.get('tel')
        studentinfo.email = request.GET.get('email')
        studentinfo.save()
    else:
        managerinfo = ManagerInformation.objects.get(manager_id=username)
        managerinfo.phone = request.GET.get('tel')
        managerinfo.email = request.GET.get('email')
        managerinfo.save()
    return JsonResponse({"label": "1"})


@decorator
def updatePwd(request):
    user = User.objects.get(name=request.session['username'])
    if (user.password == request.GET.get("oldpassword")):
        user.password = request.GET.get("newpassword")
        user.save()
        return JsonResponse({"usertype": user.user_type, "label": "1"})
    return JsonResponse({"label": "0"})


def login_out(request):
    logout(request)
    return redirect('Myauth:主页')


def exit(request):
    del request.session['username']
    return redirect('Myauth:登录')


def class_schedule(request):
    r_list = [c for c in Course_to_student.objects.filter(
        student=StudentInformation.objects.get(student=request.session.get("username")))]
    r_list += [c for c in Course_to_clbum.objects.filter(
        clbum=StudentInformation.objects.get(student=request.session.get("username")).clbum)]
    resultlist = []
    for data in r_list:
        teacher_name = data.course.teacher.name
        course_name = data.course.course_name
        course_label = data.course.course_label
        resultlist.append({
            'teacher_name': teacher_name,
            'course_name': course_name,
            'course_row': course_label % 100,
            'course_column': course_label // 100,
            'course_id': data.course.course_id,
            'course_room': data.course.course_room
        })
    return render(request, "Myauth/class_schedule.html", {'course_list': resultlist})


def class_schedule_t(request):
    r_list = CourseInformation.objects.filter(
        teacher=TeacherInformation.objects.get(teacher=request.session.get("username")))
    resultlist = []
    for data in r_list:
        resultlist.append({
            'teacher_name': data.teacher.name,
            'course_name': data.course_name,
            'course_row': data.course_label % 100,
            'course_column': data.course_label // 100,
            'course_id': data.course_id,
            'course_room': data.course_room
        })
    return render(request, "Myauth/class_schedule_t.html", {'course_list': resultlist})


def student_information(request):
    username = request.session.get('username')
    user = User.objects.get(name=username)
    if user.user_type == 1:
        studentinfo = StudentInformation.objects.get(student_id=username)
        studentinfo.clb = studentinfo.clbum.class_name
        studentinfo.department = studentinfo.clbum.department.department_name
        return render(request, 'Myauth/Student_Information.html', {'studentinfo': studentinfo})


def teacher_information(request):
    username = request.session.get('username')
    user = User.objects.get(name=username)
    if user.user_type == 2:
        # student = StudentInformation()
        # student.get_Gender_display()
        teacherinfo = TeacherInformation.objects.get(teacher_id=username)
        teacherinfo.depart = teacherinfo.department.department_name
        return render(request, 'Myauth/Teacher_Information.html', {'teacherinfo': teacherinfo})


def manager_information(request):
    username = request.session.get('username')
    user = User.objects.get(name=username)
    if user.user_type == 0:
        # student = StudentInformation()
        # student.get_Gender_display()
        managerinfo = ManagerInformation.objects.get(manager_id=username)
        return render(request, 'Myauth/Manager_Information.html', {'managerinfo': managerinfo})


def get_classschedule(request):
    pass


def input_course_m(request, pIndex='1'):
    datalist = TeacherInformation.objects.all()
    teacherlist = []
    for data in datalist:
        teacherlist.append({
            "teacher": data.teacher,
            "teacher_name": data.name
        })
    resultlist = CourseInformation.objects.all()
    p = Paginator(resultlist, 10)
    if pIndex == '':
        pIndex = '1'
    pIndex = int(pIndex)

teaching_management/templates/Myauth/Student_Information.html
{% extends 'Myauth/base.html' %}
{% load staticfiles %}

{% block style %}
<style>
    td{
        text-align: center;
        cursor: default;
    }
</style>
{% endblock %}

{% block student %}
<div style="margin:20px 0;">
    <a href="#" id="update_stuinfo" class="easyui-linkbutton" data-options="iconCls:'icon-edit'" style="margin-left: 45%">修改</a>
    <a href="#" id="save_stuinfo" class="easyui-linkbutton" data-options="iconCls:'icon-save'" style="margin-left: 0%">保存</a>
    <a href="#" onclick='tableToExcel()' id="save_excel" class="easyui-linkbutton" style="margin-left: 0%">excel</a>
</div>
<table id="table_wrapper" width=60% height=70%  bgcolor=#ccc cellspacing="3" align="center">
    <tr bgcolor="white">
        <td>学号</td>
        <td>{{studentinfo.student_id}}</td>
    </tr>
    <tr bgcolor="white">
        <td>姓名</td>
        <td>{{studentinfo.name}}</td>
    </tr>
    <tr bgcolor="white">
        <td>性别</td>
        <td>{{studentinfo.sex}}</td>
    </tr>
    <tr bgcolor="white">
        <td>出生日期</td>
        <td>{{studentinfo.birthday}}</td>
    </tr>
    <tr bgcolor="white">
        <td>学院</td>
        <td>{{studentinfo.department}}</td>
    </tr>
    <tr bgcolor="white">
        <td>入学日期</td>
        <td>{{studentinfo.admission_date}}</td>
    </tr>
    <tr bgcolor="white">
        <td>班级</td>
        <td>{{studentinfo.clb}}</td>
    </tr>
    <tr bgcolor="white">
        <td>电话</td>
        <td><input id="tel" readonly="readonly" style="border:0px;outline: none;height:100%;line-height:100%;" value={{studentinfo.phone}} /></td>
    </tr>
    <tr bgcolor="white">
        <td>邮箱</td>
        <td><input id="email" readonly="readonly" style="border:0px;outline: none;height:100%;line-height:100%;" value={{studentinfo.email}} /></td>
    </tr>
</table>


<script>
        var label = false
		$(function(){
			$('#menu2').addClass('active')
			$('#allmenu').accordion('select', '个人信息')
		})
		$("#update_stuinfo").click(function(){
		    label = true
            document.getElementById("tel").removeAttribute("readOnly")
            document.getElementById("email").removeAttribute("readOnly")
            })

        $("#save_stuinfo").click(function(){
            var url = "{% url 'Myauth:修改个人信息' %}"
            if(label==false){return false}
            $.get(url, {'tel':document.getElementById("tel").value , 'email':document.getElementById("email").value}, function(data){
                if (data.label=="1"){
                	alert("信息修改成功！")
                	location.reload();
                }
                else{
                    alert("信息修改失败");
                    location.reload();
                }
            })
        })

       function tableToExcel(){
      //要导出的json数据
      const jsonData = [
        {
          name:'{{studentinfo.name|safe}}',
          sex:'{{studentinfo.sex|safe}}',
          student_id:'{{studentinfo.student_id|safe}}',
          birthday:'{{studentinfo.birthday|safe}}',
          department:'{{studentinfo.department|safe}}',
          admission_date:'{{studentinfo.admission_date|safe}}',
          clbum:'{{studentinfo.clbum|safe}}',
          phone:'{{studentinfo.phone|safe}}',
          email:'{{studentinfo.email|safe}}',
        }
      ]
      //列标题
      let str = '<tr><td>姓名</td><td>性别</td><td>学号</td><td>出生日期</td><td>学院</td><td>入学日期</td><td>班级</td><td>电话</td><td>邮箱</td></tr>';
      //循环遍历，每行加入tr标签，每个单元格加td标签
      for(let i = 0 ; i < jsonData.length ; i++ ){
        str+='<tr>';
        for(let item in jsonData[i]){
            //增加\t为了不让表格显示科学计数法或者其他格式
            str+=`<td>${ jsonData[i][item] + '\t'}</td>`;
        }
        str+='</tr>';
      }
      //Worksheet名
      let worksheet = 'Sheet1'
      let uri = 'data:application/vnd.ms-excel;base64,';

      //下载的表格模板数据
      let template = `<html xmlns:o="urn:schemas-microsoft-com:office:office"
      xmlns:x="urn:schemas-microsoft-com:office:excel"
      xmlns="http://www.w3.org/TR/REC-html40">
      <head><!--[if gte mso 9]><xml><x:ExcelWorkbook><x:ExcelWorksheets><x:ExcelWorksheet>
        <x:Name>${worksheet}</x:Name>
        <x:WorksheetOptions><x:DisplayGridlines/></x:WorksheetOptions></x:ExcelWorksheet>
        </x:ExcelWorksheets></x:ExcelWorkbook></xml><![endif]-->
        </head><body><table>${str}</table></body></html>`;
      //下载模板
      window.location.href = uri + base64(template)
    }
    //输出base64编码
    function base64 (s) { return window.btoa(unescape(encodeURIComponent(s))) }

</script>

{% endblock %}

teaching_management/templates/Myauth/analysescore.html
{% extends 'Myauth/base_t.html' %}
{% load staticfiles %}
{% block teacher %}
{% block style %}
<style>
	.register-body{
		margin-left: 30%;
	}
	.left{
	    width:150px;
	    height:35px;
	    line-height:35px;
	    margin-right:20px;
	    color:#000;
	    text-align:center;
	}

	.right{
	    width:150px;
	    height:35px;
	    line-height:35px;
	    color:#000;
	    text-align:center;
	}
</style>
{% endblock %}
<table id="table_wrapper" toolbar="#toolbox" iconCls="icon-search" rownumbers="true" pagination="true">
	<thead>
		<tr>
<!--			TODO 待修改-->
			<th field="course_id" width="178" align="center">课程号</th>
			<th field="course_id" width="178" align="center">课程类型</th>
			<th field="course_name" width="178" align="center">课程名称</th>
            <th field="course_teacher" width="178" align="center">平均分</th>
            <th field="course_teacher" width="178" align="center">最高分</th>
            <th field="course_teacher" width="178" align="center">最低分</th>
			<th field="course_teacher" width="178" align="center">难度</th>
			<th field="course_teacher" width="323" align="center">图表</th>
		</tr>
	</thead>
	<tbody id="table_body">
	{%for data in datalist%}
	<tr class="trbody">
		<td width="178" align="center"><input type="checkbox" name="courseID" value="{{data.course_id}}" />{{data.course_id}}</td>
		<td width="178" align="center">{{data.course_type}}</td>
		<td width="178" align="center">{{data.course_name}}</td>
        <td width="178" align="center">{{data.meanscore}}</td>
		<td width="323" align="center">{{data.maxscore}}</td>
        <td width="323" align="center">{{data.minscore}}</td>
		<td width="178" align="center">{{data.scorelabel}}</td>
		<td width="323" align="center"><input class="scorebtn" type="button" value="成绩关联图" /><a href="/scorelayer/?type={{data.course_id}}">成绩分布</a></td>
	</tr>
	{%endfor%}
	<div><input id="compare" type="button" value="显示分析图"/></div>
	<div><input id="comparebtn" type="button" value="综合比较" /></div>
	</tbody>
</table>
<script>


    $(function(){
        $('#menu7').addClass('active')
        $('#allmenu').accordion('select', '老师成绩分析')
    });

	$("#compare").click(function(){
		location.href = "{% url 'Myauth:成绩总图' %}"
	})

	$(".scorebtn").click(function(){
		let data = $(this).parent().parent().children().eq(0).text()
		let url = "{% url 'Myauth:各班级优生率' %}"
		$.get(url, {'type':data}, function(data){
			if(data=="1"){
				location.href = "{% url 'Myauth:单科总图' %}"
			}
		})
	})

	$("#comparebtn").click(function(){
		if($("input[name='courseID']:checked").length<=1){
			alert("必须选中2个科目以上")
			return false
		}
		let id_list = []
		let label_list = []
		$("input[name='courseID']:checked").each(function(){
			id_list.push($(this).val())
			label_list.push($(this).parent().parent().children().eq(6).text())
		})
		let url = "{% url 'Myauth:综合比较' %}"
		$.get(url, {'id_list':id_list,'label_list':label_list}, function(data){
			if(data=="1"){
				location.href = "{% url 'Myauth:综合比较页' %}"
			}
		})
	})
</script>
{% endblock %}

teaching_management/templates/Myauth/base_m.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>管理员系统模板</title>
    <link rel="stylesheet" type="text/css" href="{% static 'jquery-easyui-1.7.0/themes/default/easyui.css'%}">
    <link rel="stylesheet" type="text/css" href="{% static 'jquery-easyui-1.7.0/themes/icon.css' %}">
    <script type="text/javascript" src="{% static 'jquery-easyui-1.7.0/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'jquery-easyui-1.7.0/jquery.easyui.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/laydate.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/xlsx.core.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/xlsx.full.min.js' %}"></script>
    <style>
        .panel.layout-panel.layout-panel-west.panel-htop.layout-split-west{
            width: 150px !important;
        }

        .my-menu{
            display: block;
            padding: 6px;
            border-bottom: 1px solid #ddd;
        }

        a:link {
            font-size: 12px;
            color: #000000;
            text-decoration: none;
        }
        a:visited {
            font-size: 12px;
            color: #000000;
            text-decoration: none;
        }
        a:hover {
            font-size: 12px;
            color: #999999;
        }
        .active{
            background: #c0cde9;
            color: white;
        }
    </style>
    {% block style %}
    {% endblock %}
</head>
<body class="easyui-layout" style="margin-left: 10px;margin-right: 10px;">
<div style="margin:20px 0;"></div>
<div class="easyui-layout" style="width:100%;height:100%;position:fixed;">
    <div data-options="region:'north'" style="height:50px" title="蒹葭教学管理系统"></div>
    <div data-options="region:'south',split:true" style="height:50px;"></div>
    <div data-options="region:'west',split:true" title="导航栏" style="width:100px;">
        <div id='allmenu' class="easyui-accordion" data-options="fit:true,border:false,selected:0">
            <div id="usermenu" title="用户菜单"  style="padding:10px;">
                <a class="my-menu" id="menu1" href="{% url 'Myauth:登录' %}">退出系统</a>
                <a class="my-menu" id="menu2" href="{% url 'Myauth:管理员信息' %}">管理员个人信息</a>
                <a class="my-menu" id="menu3" href="{% url 'Myauth:修改密码' %}">修改密码</a>
                <a class="my-menu" id="menu4" href="{% url 'Myauth:审核个人信息' %}">审核个人信息</a>
                <a class="my-menu" id="menu5" href="{% url 'Myauth:注册' %}">注册</a>
            </div>
            <div id="courseinfo" title="课程信息"  style="padding:10px;">
                <a class="my-menu" id="menu6" href="/pag1/">录入课程</a>
                <a class="my-menu" id="menu7" href="/search1/">查看课程</a>
            </div>
            <div id="testinfo" title="考试信息"  style="padding:10px;">
                <a class="my-menu" id="menu8" href="{% url 'Myauth:考试编排页' %}">考试编排</a>
                <a class="my-menu" id="menu9" href="{% url 'Myauth:录入成绩页' %}">录入成绩</a>
                <a class="my-menu" id="menu10" href="{% url 'Myauth:查看考试信息' %}">查看考试信息</a>

            </div>
        </div>
    </div>
    <div data-options="region:'center',title:'内容',iconCls:'icon-lock'">
        {% block manager %}
        {% endblock %}
        {% block content %}
        {% endblock %}
    </div>
</div>
</body>
</html>

teaching_management/templates/Myauth/homepage_m.html
{% extends 'Myauth/base_m.html' %}
{% block manager %}
<div style="font-size: 60px;" class="center">欢迎管理员{{ managerinfo.name }}登录！！</div>
{% endblock %}

teaching_management/templates/Myauth/selectstudentscore.html
{% extends 'Myauth/base.html' %}
{% load staticfiles %}
{% block student %}
{% block style %}
<style>
	.register-body{
		margin-left: 30%;
	}
</style>
{% endblock %}
<table id="table_wrapper" toolbar="#toolbox" iconCls="icon-search" rownumbers="true" pagination="true">
	<thead>
		<tr>
<!--			TODO 待修改-->
			<th field="course_id" width="178" align="center">课程号</th>
			<th field="course_id" width="178" align="center">课程类型</th>
			<th field="course_name" width="178" align="center">课程名称</th>
            <th field="course_name" width="178" align="center">任课老师</th>
			<th field="course_credit" width="323" align="center">班级</th>
			<th field="course_teacher" width="178" align="center">分数</th>
		</tr>
	</thead>
	<tbody id="table_body">
	{%for data in datalist%}
	<tr class="trbody">
		<td width="178" align="center">{{data.course_id}}</td>
		<td width="178" align="center">{{data.course_type}}</td>
		<td width="178" align="center">{{data.course_name}}</td>
        <td width="178" align="center">{{data.teacher_name}}</td>
		<td width="323" align="center">{{data.class_name}}</td>
		<td width="178" align="center">{{data.score}}</td>
	</tr>
	{%endfor%}
	</tbody>
</table>
{% endblock %}